### Mandatory Input Files ###
# Set as folder containing BAMs to process
input_bam_folder: "/path/to/folder"

### Optional Input Files ###
# Folder containing text files which pre-determine the cell barcodes to use in each sample's pseudoreplicates
# e.g. "path/to/barcodes/barcode_split_b-cell.txt" must contain tab separated cell barcodes and pseudoreplicate IDs 
# (no header or index) to split file "b-cell.bam"
barcode_preset_folder: None

### Output Folders ###
# Folders to create which results and temporary files will be saved to
result_folder: "Results"
temp_folder: "Temp"
# Sub-folders to be created to store each result type
barcode_count_folder: "Barcode_Counts"
barcode_split_folder: "Barcode_Split"
pseudorep_folder: "Pseudoreplicates"
summary_folder: "Summary"

### Splitting into Pseudoreplicates ###
# Seed for random number generation
random_seed: 1
# Set name of cell barcode tag within BAM file (usually this is CB)
barcode_tag: "CB"
# Number of cells to include in a pseudoreplicate
pseudo_size: 500
# Only BAM files which have enough unique cells to create this minimum number of pseudoreplicates will be split
# e.g. if "b-cell.bam" has 1241 unique cell barcodes and min_replicates = 3 with pseudo_size = 500, then 
# this file will be skipped as it has less than 3 * 500 unqiue cells
min_replicates: 1

### Normalisation Parameters ###
# Normalisation method to use in bamCoverage
norm_method: "None"
# Bin size to use in bamCoverage
bin_size: 1
# LanceOtron, MACS3 or None
peak_caller: "macs3"

### Parallalisation ###
# Max number of cores to use for steps which can use multi-processing
subprocess_threads: 4
